package com.smartwater.backend.controller;

import com.smartwater.backend.model.PollutionReport;
import com.smartwater.backend.service.PollutionReportService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/reports")
@CrossOrigin(origins = "*")
public class PollutionReportController {

    @Autowired
    private PollutionReportService reportService;


    @PostMapping
    public Map<String, Object> createReport(
            @AuthenticationPrincipal UserDetails currentUser,
            @RequestBody Map<String, String> body
    ) {
        String email = currentUser.getUsername();
        String description = body.get("description");
        String photoUrl = body.get("photoUrl");
        String location = body.get("location");

        if (description == null || description.trim().isEmpty()) {
            throw new RuntimeException("Description is required.");
        }

        PollutionReport report = reportService.createReport(email, description, photoUrl, location);

        Map<String, Object> response = new HashMap<>();
        response.put("message", "Report submitted successfully.");
        response.put("id", report.getId());
        response.put("description", report.getDescription());
        response.put("photoUrl", report.getPhotoUrl());
        response.put("location", report.getLocation());
        response.put("status", report.getStatus());
        response.put("createdAt", report.getCreatedAt());
        response.put("autoGenerated", report.getAutoGenerated());
        response.put("adminComment", report.getAdminComment());
        response.put("resolvedAt", report.getResolvedAt());

        return response;
    }


    @GetMapping("/me")
    public List<PollutionReport> getMyReports(@AuthenticationPrincipal UserDetails currentUser) {
        String email = currentUser.getUsername();
        return reportService.getReportsForUser(email);
    }


    @GetMapping
    public List<PollutionReport> getAllReports() {
        return reportService.getAllReports();
    }


    @PutMapping("/{id}/status")
    public PollutionReport updateReportStatus(
            @PathVariable Long id,
            @RequestBody Map<String, String> body
    ) {
        String newStatus = body.get("status");
        String adminComment = body.get("adminComment");

        if (newStatus == null || newStatus.trim().isEmpty()) {
            throw new RuntimeException("Status is required.");
        }

        return reportService.updateReportStatus(id, newStatus, adminComment);
    }
}
