PUT http://localhost:8080/api/reports/1/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZDIwMDZ5eGNAMTYzLmNvbSIsImlhdCI6MTc2NDk5NTYxNywiZXhwIjoxNzY1MDgyMDE3fQ.O1QGaAwk3aeMdlz1kjMcmSqq7zWjUfNcbh_6QygRx3s
Content-Type: application/json

{
  "status": "ABC"
}
