package com.smartwater.backend.dto;

import java.time.LocalDateTime;

public class PollutionReportResponse {

    private Long id;
    private String description;
    private String photoUrl;
    private String location;
    private String status;
    private LocalDateTime createdAt;
    private Boolean autoGenerated;
    private String adminComment;
    private LocalDateTime resolvedAt;



    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getPhotoUrl() { return photoUrl; }
    public void setPhotoUrl(String photoUrl) { this.photoUrl = photoUrl; }

    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public Boolean getAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(Boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public String getAdminComment() { return adminComment; }
    public void setAdminComment(String adminComment) { this.adminComment = adminComment; }

    public LocalDateTime getResolvedAt() { return resolvedAt; }
    public void setResolvedAt(LocalDateTime resolvedAt) { this.resolvedAt = resolvedAt; }
}
