package com.smartwater.backend.service;

import com.smartwater.backend.dto.PollutionReportResponse;
import com.smartwater.backend.exception.BadRequestException;
import com.smartwater.backend.exception.NotFoundException;
import com.smartwater.backend.model.PollutionReport;
import com.smartwater.backend.model.User;
import com.smartwater.backend.repository.PollutionReportRepository;
import com.smartwater.backend.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

@Service
public class PollutionReportService {

    @Autowired
    private PollutionReportRepository reportRepository;

    @Autowired
    private UserRepository userRepository;

    public PollutionReport createReport(
            String userEmail,
            String description,
            String photoUrl,
            String location
    ) {
        return createReport(userEmail, description, photoUrl, location, false);
    }

    public PollutionReport createReport(
            String userEmail,
            String description,
            String photoUrl,
            String location,
            boolean autoGenerated
    ) {
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new NotFoundException("User not found with email: " + userEmail));

        PollutionReport report = new PollutionReport();
        report.setUser(user);
        report.setDescription(description);
        report.setPhotoUrl(photoUrl);
        report.setLocation(location);
        report.setAutoGenerated(autoGenerated);

        return reportRepository.save(report);
    }

    public List<PollutionReport> getReportsForUser(String userEmail) {
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new NotFoundException("User not found with email: " + userEmail));

        return reportRepository.findByUserOrderByCreatedAtDesc(user);
    }

    public List<PollutionReport> getAllReports() {
        return reportRepository.findAll();
    }

    public PollutionReport updateReportStatus(Long reportId, String newStatus, String adminComment) {

        PollutionReport report = reportRepository.findById(reportId)
                .orElseThrow(() -> new NotFoundException("Report not found with id: " + reportId));

        if (!"OPEN".equalsIgnoreCase(newStatus)
                && !"IN_REVIEW".equalsIgnoreCase(newStatus)
                && !"RESOLVED".equalsIgnoreCase(newStatus)) {
            throw new BadRequestException(
                    "Invalid status: " + newStatus + ". Allowed values: OPEN, IN_REVIEW, RESOLVED"
            );
        }

        report.setStatus(newStatus.toUpperCase());

        if (adminComment != null && !adminComment.trim().isEmpty()) {
            report.setAdminComment(adminComment.trim());
        }

        if ("RESOLVED".equalsIgnoreCase(newStatus)) {
            report.setResolvedAt(LocalDateTime.now());
        }

        return reportRepository.save(report);
    }

    public PollutionReportResponse toResponse(PollutionReport report) {
        PollutionReportResponse dto = new PollutionReportResponse();
        dto.setId(report.getId());
        dto.setDescription(report.getDescription());
        dto.setPhotoUrl(report.getPhotoUrl());
        dto.setLocation(report.getLocation());
        dto.setStatus(report.getStatus());
        dto.setCreatedAt(report.getCreatedAt());
        dto.setAutoGenerated(report.getAutoGenerated());
        dto.setAdminComment(report.getAdminComment());
        dto.setResolvedAt(report.getResolvedAt());
        return dto;
    }
}
